### ISSUE TITLE
when keyboard open search doesnt show up 

### ISSUE THREAD

**Issue by egecetiner** [AstrOOnauta/react-native-international-phone-number#85] opened 2024-06-10 08:39 UTC
My modal height is 90% and when i open focus search input keyboard padding make search lose. i should be able to close keyboard padding.

**Comment by AstrOOnauta** [comment] 2024-10-22 19:38
Please send me more information about this, like a video, for investigation.

**Comment by AstrOOnauta** [comment] 2024-11-19 22:58
I could not reproduce it. As I haven't had any more answers about this case, I'm closing this issue.

**Closed by AstrOOnauta** 2024-11-19 22:58 UTC
Labels: help wanted
